#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_TOUCHSCREEN_TIMER_PERIOD 5.0E-3
#define CONFIG_GAME_TIMER_PERIOD 45.0E-3

#define CONFIG_BOX_KEYBOARD_X_0 4
#define CONFIG_BOX_KEYBOARD_X_1 312
#define CONFIG_BOX_KEYBOARD_Y_0 155
#define CONFIG_BOX_KEYBOARD_Y_1 80
#define CONFIG_LINE_KEYBOARD 195
#define CONFIG_LINE_KEYBOARD_Y 235
#define CONFIG_LINE_VERTICLE_LETTER_SPACE 24
#define CONFIG_LETTER_Y_TOP 165
#define CONFIG_LETTER_Y_BOTTOM 205

#define CONFIG_BOX_GALLOWS_X_0 200
#define CONFIG_BOX_GALLOWS_X_1 120
#define CONFIG_BOX_GALLOWS_Y_0 0
#define CONFIG_BOX_GALLOWS_Y_1 120

#define CONFIG_LENGTH_GALLOWS_BASE_X 220
#define CONFIG_LENGTH_GALLOWS_BASE_Y 110
#define CONFIG_LENGTH_GALLOWS_POLE_X 296
#define CONFIG_LENGTH_GALLOWS_POLE_Y 10

#define CONFIG_LENGTH_GALLOWS_BEAM_X 246

#define CONFIG_LENGTH_GALLOWS_ROPE_Y 35

#define CONFIG_MAN_HEAD 5
#define CONFIG_MAN_HEAD_Y (CONFIG_LENGTH_GALLOWS_ROPE_Y + CONFIG_MAN_HEAD)
#define CONFIG_LENGTH_MAN_BODY_Y_0 (CONFIG_LENGTH_GALLOWS_ROPE_Y + CONFIG_MAN_HEAD * 2)
#define CONFIG_LENGTH_MAN_BODY_Y_1 (CONFIG_LENGTH_GALLOWS_ROPE_Y + CONFIG_MAN_HEAD * 2 + 22)

#define CONFIG_LENGTH_MAN_ARM_Y_0 (CONFIG_MAN_HEAD_Y + 8)
#define CONFIG_LENGTH_MAN_ARM_Y_1 (CONFIG_MAN_HEAD_Y + 18)
#define CONFIG_LENGTH_MAN_ARM_0_X_1 (CONFIG_LENGTH_GALLOWS_BEAM_X - 15)
#define CONFIG_LENGTH_MAN_ARM_1_X_1 (CONFIG_LENGTH_GALLOWS_BEAM_X + 15)

#define CONFIG_LENGTH_MAN_LEG_0_X_1 (CONFIG_LENGTH_GALLOWS_BEAM_X - 12)
#define CONFIG_LENGTH_MAN_LEG_1_X_1 (CONFIG_LENGTH_GALLOWS_BEAM_X + 12)
#define CONFIG_LENGTH_MAN_LEG_Y_1 (CONFIG_LENGTH_MAN_BODY_Y_1 + 16)

#define CONFIG_CORRECT_LETTER_HEIGHT 144
#define CONFIG_CORRECT_LETTER_LINE 21

#define CONFIG_COLOR_MAN DISPLAY_RED
#define CONFIG_BOX_COLOR DISPLAY_DARK_GREEN
#define CONFIG_GALLOWS_COLOR DISPLAY_GRAY
#define CONFIG_COLOR_TEXT DISPLAY_WHITE
#define CONFIG_COLOR_USED_TEXT DISPLAY_GRAY

#define CONFIG_BACKGROUND_COLOR DISPLAY_BLACK

#define OFFSET_TRI 0x04
#define OFFSET_DATA 0x00
#define TRI_WRITE_I 0x0F
#define Y_TEXT_0 30
#define Y_TEXT_1 50
#define Y_TEXT_2 70
#define TEXT_SIZE 2
#define X_TEXT 4




#endif /* CONFIG_H */
