name: CI
on: push

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo pip3 install cmake
        sudo apt-get update
        sudo apt-get install -y qt5-default gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib clang-format-6.0
    - name: Compile emulator
      run: cd build && rm -rf ./* && cmake .. -DEMU=1 && make -j4  
    - name: Compile Zybo
      run: cd build && rm -rf ./* && cmake .. && make -j4
    - name: Check C/C++ formatting
      run: ./format.py --check --all
    - name: Run check_and_zip.py
      run: ./check_and_zip.py --no_run lab1
